import { REPORT_COST, SIGNUP_BONUS, CREDIT_COSTS } from "@/lib/credit-costs";
import { DEMO_REPORT_SLUG } from "@/lib/demo-report";

export const DEMO_REPORT_HREF = `/report/${DEMO_REPORT_SLUG}`;

export const TRUST_CHIPS = [
  "Explainable recommendations",
  "Real catalogue links",
  "GDPR-first",
  "Brand face · inspired by Carlo Valetti",
  "Human-informed style rules",
] as const;

export const METHODOLOGY_STEPS = [
  {
    title: "Photos & questionnaire",
    body: "Front portrait, full length, and honest answers on lifestyle, goals and budget. Hair and eye colour sharpen the analysis when you add them.",
  },
  {
    title: "Style Profile",
    body: "Vision reads colouring and proportions. Styling rules (SRE) ground recommendations — not a generic chat reply.",
  },
  {
    title: "Explainable report",
    body: "Every important colour, haircut and silhouette call includes a concrete why tied to your profile.",
  },
  {
    title: "Shopping & try-on",
    body: "Looks matched to your palette from our catalogue — with links you can open, and try-on on your own photo.",
  },
] as const;

export const CARLO_CREDENTIALS = [
  {
    title: "Explainability",
    body: "Why on colours, hair, fit and shopping — so you learn the method, not just follow orders.",
  },
  {
    title: "Human-informed rules",
    body: "Colour, fit, climate and tone-of-voice shaped with stylist input — the engine applies them consistently.",
  },
  {
    title: "Honest AI",
    body: "Carlo is Valetti's brand face and voice. Analysis is AI-assisted; we say so openly, everywhere.",
  },
] as const;

export const REPORT_PROOF_CARDS = [
  {
    eyebrow: "Start here",
    title: "3 changes with the highest return",
    body: "Replace black-and-white contrast with warm neutrals, keep silhouettes tailored, and make brown leather your default.",
  },
  {
    eyebrow: "Colour diagnosis",
    title: "Soft Autumn, not generic autumn",
    body: "Warm, muted, low-contrast colours make the face look healthier; optic white and cold black drain the complexion.",
  },
  {
    eyebrow: "Hair direction",
    title: "Texture over severity",
    body: "A textured crop and softer side profile sharpen the face without making the look feel corporate or dated.",
  },
  {
    eyebrow: "Buying plan",
    title: "Good · Better · Best shopping",
    body: "The report turns analysis into a practical capsule: what to buy first, what can wait, and where to spend.",
  },
] as const;

export const WHY_THIS_WORKS = [
  {
    id: "colour",
    label: "Colour",
    call: "Swap optic white and black for warm ecru and tobacco brown near the face.",
    why: "Soft Autumn skin reads healthier when contrast stays soft. Cold black and bright white overpower warm, muted colouring and highlight fatigue.",
    action: "Use the palette chips in your report when buying tees, shirts and knits.",
    imageBefore: "/images/hero-editorial-bad-palette.png",
    imageAfter: "/images/hero-editorial.png",
    useSlider: true,
  },
  {
    id: "hair",
    label: "Hair",
    call: "Choose texture and softness over a severe, high-contrast crop.",
    why: "Oval face + low contrast: hard lines and slicked severity fight your natural colouring. A textured crop adds structure without ageing the look.",
    action: "Show your barber the recommended and avoid previews from the report.",
    imageBefore: "/images/demo/hair-buzz-cut-avoid.png",
    imageAfter: "/images/demo/hair-textured-crop-side.png",
    useSlider: false,
  },
  {
    id: "shopping",
    label: "Shopping",
    call: "Brown leather derbies instead of black — they tie the warm palette together.",
    why: "Black footwear often breaks a Soft Autumn outfit. Warm brown reads dressier than black here and repeats across work, dinner and weekend looks.",
    action: "Start with the Good tier in your shopping list, then try on before you buy more.",
    imageBefore: "/images/products/brown-derbies.png",
    imageAfter: "/images/look-work.png",
    useSlider: false,
  },
] as const;

export const TRUST_PIPELINE = [
  {
    step: "Private upload",
    detail: "Photos stored for your account only. Explicit consent before analysis.",
  },
  {
    step: "AI analysis",
    detail: "Vision + rules + catalogue matching — not a single generic prompt.",
  },
  {
    step: "Your report",
    detail: "Structured sections you can share, export, or act on immediately.",
  },
  {
    step: "Delete anytime",
    detail: "Export or erase your data from account settings — GDPR by design.",
  },
] as const;

export const TESTMAIN_FAQS = [
  {
    q: "Is Carlo a real person?",
    a: "Carlo Valetti is Valetti's brand face — the calm voice in every report, inspired by a European private-stylist archetype. Recommendations are generated by Valetti's analysis engine; Carlo presents them in plain language with the reason behind each call.",
  },
  {
    q: "How is this different from ChatGPT fashion advice?",
    a: "Valetti builds a structured Style Profile from your photos and questionnaire, applies human-informed styling rules, matches real catalogue products, and generates photorealistic looks on your photo. Every major call is explainable — not a one-off paragraph.",
  },
  {
    q: "Can I trust the colour analysis?",
    a: "We use undertone, contrast, hair and eye colour, and a 12-subseason model — then show you the why on each palette swatch. The demo report includes a before/after palette comparison so you can judge the logic yourself.",
  },
  {
    q: "What's included in a report?",
    a: "Depending on tier: style profile, colour palette with reasons, hair and grooming guidance, photorealistic looks, capsule wardrobe, shopping list with real links, PDF export, and virtual try-on.",
  },
  {
    q: "Are my photos private?",
    a: "Yes. GDPR-first by design. Photos are used only to generate your report. You can export or delete your data at any time.",
  },
  {
    q: "Do you show real user reviews?",
    a: "We do not invent testimonials. When enough verified feedback exists, we will show aggregated ratings and opt-in quotes. Until then, we prove quality through the public demo report and the methodology on this page.",
  },
] as const;

export const HERO_PROOF = {
  season: "Soft Autumn",
  undertone: "Warm undertone",
  contrast: "Low contrast",
  moves: [
    "Warm navy over black near the face",
    "Cream knit instead of optic white",
    "Brown leather as your default shoe",
  ],
} as const;

export const SIGNUP_LINE = `Sign up for ${SIGNUP_BONUS} free credits — Starter Report ${REPORT_COST.free} credits, try-on ${CREDIT_COSTS.tryon} credit · No subscription`;
