import { StylistNote } from "@/components/StylistNote";
import { BRAND } from "@/lib/brand";
import { METHODOLOGY_STEPS } from "@/lib/marketing/testmain-content";

export function MethodologySection() {
  return (
    <section id="methodology" className="container-luxe scroll-mt-24 py-24">
      <div className="max-w-2xl">
        <p className="eyebrow">Methodology</p>
        <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
          How {BRAND.stylist.first} works for men — and what the engine does.
        </h2>
        <p className="mt-4 text-lg leading-relaxed text-stone">
          Tailoring, grooming and menswear rules — proven through method, not
          mystery. Here is the path from your photos to a shopping list you can
          act on.
        </p>
      </div>

      <div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-4">
        {METHODOLOGY_STEPS.map((step, i) => (
          <article key={step.title} className="relative">
            <div className="font-display text-5xl text-sand">
              {String(i + 1).padStart(2, "0")}
            </div>
            <h3 className="mt-3 font-display text-xl">{step.title}</h3>
            <p className="mt-2 text-sm leading-relaxed text-stone">{step.body}</p>
          </article>
        ))}
      </div>

      <div className="mt-12">
        <StylistNote>
          <p className="text-sm leading-relaxed">
            I don&apos;t guess. Every colour, haircut and silhouette call ties
            back to your undertone, contrast, face shape and goals — and I tell
            you why. The analysis is AI-assisted; my job is to make it readable
            and actionable.
          </p>
        </StylistNote>
      </div>

      <p className="mt-6 max-w-2xl text-xs leading-relaxed text-stone-soft">
        {BRAND.stylist.name} is {BRAND.name}&apos;s brand face — inspired by a
        private-stylist archetype. Recommendations are generated by
        Valetti&apos;s engine and styling rules; Carlo is the voice, not a
        substitute for in-person fitting when you need one.
      </p>
    </section>
  );
}
