import Image from "next/image";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { MeetStylist } from "@/components/MeetStylist";
import { ButtonLink } from "@/components/Button";
import { ImageComparisonSlider } from "@/components/ImageComparisonSlider";
import { SubCurrencyPrice } from "@/components/SubCurrencyPrice";
import {
  REPORT_COST,
  CREDIT_COSTS,
  CREDIT_PACKAGES,
  SIGNUP_BONUS,
} from "@/lib/credit-costs";
import { lookCountForTier } from "@/lib/report";
import { LOOK_SET_BUNDLES } from "@/lib/look-sets";
import { BRAND } from "@/lib/brand";
import {
  organizationJsonLd,
  serviceJsonLd,
  websiteJsonLd,
} from "@/lib/site-json-ld";
import { absoluteUrl } from "@/lib/site-url";

const CONSTRUCTOR_ASSETS = [
  { src: "/images/products/olive-overshirt.png", label: "Jacket" },
  { src: "/images/products/charcoal-trousers.png", label: "Trousers" },
  { src: "/images/products/chelsea-boots.png", label: "Shoes" },
  { src: "/images/demo/accessory-tie.png", label: "Tie" },
  { src: "/images/products/field-watch.png", label: "Watch" },
] as const;

const FAQS: { q: string; a: string }[] = [
  {
    q: "Is Valetti only for men?",
    a: "Yes. Valetti is built for men's personal styling — tailoring, menswear silhouettes, grooming and shopping. The questionnaire uses male fit rules by design.",
  },
  {
    q: "Is Valetti a real stylist or AI?",
    a: "Carlo Valetti is our lead stylist persona — the voice in every report. Recommendations are generated by Valetti's analysis engine; Carlo presents them in plain language, with the reason behind each call. The service is AI-assisted, and we say so openly.",
  },
  {
    q: "What's included in a report?",
    a: "Depending on tier: a structured style profile, a colour palette with reasons, hair, beard and eyewear guidance, photorealistic looks, a capsule wardrobe with a week-of-outfits matrix, and a shopping list with real product links and virtual try-on.",
  },
  {
    q: "Do I need a subscription?",
    a: "No. Valetti runs on credits that never expire. New accounts get 6 free credits — enough for your first Starter Report and a try-on. Buy more only when you need them.",
  },
  {
    q: "Are my photos private?",
    a: "Yes. Your face and body are sensitive data, so Valetti is built GDPR-first. Photos are used only to generate your report, and any affiliate links are disclosed.",
  },
  {
    q: "How accurate are the recommendations?",
    a: "Every important call is explainable — grounded in your colouring, proportions, lifestyle and goals — so you understand why a look suits you, not just that it does.",
  },
  {
    q: "Can I actually buy the looks?",
    a: "Yes. Each report includes a shopping list matched to your palette from our catalogue, with real product links and a Good · Better · Best buying plan that tells you where to spend.",
  },
  {
    q: "Can I generate looks without a full report?",
    a: "Yes. Create a Look builds a set of 3, 6 or 9 photorealistic outfits on your photo for an occasion. Open any look and use the constructor to change a jacket, colour, sunglasses, tie or whether a shirt is tucked in — then redraw just that look.",
  },
  {
    q: "Can I try catalogue pieces on myself?",
    a: "Yes. Sign in, add a full-length photo, then pick up to four items in the catalogue and render them together on your photo — on the original scene or in a clean studio. One credit per try-on.",
  },
];

export default function Home() {
  return (
    <>
      <JsonLd />
      <Navbar />
      <main className="flex-1">
        <Hero />
        <Marquee />
        <Problem />
        {/* <ReportProof /> */}
        <MeetStylist />
        <Understand />
        <ImpactOfColour />
        <HowItWorks />
        <SampleReport />
        <LooksStudio />
        <CapsulePreview />
        <Audience />
        <Pricing />
        <Principles />
        <Faq />
        <FinalCTA />
      </main>
      <Footer />
    </>
  );
}

function JsonLd() {
  const site = absoluteUrl("/");
  const data = {
    "@context": "https://schema.org",
    "@graph": [
      organizationJsonLd(site),
      websiteJsonLd(site),
      serviceJsonLd(site),
      {
        "@type": "FAQPage",
        mainEntity: FAQS.map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      },
    ],
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

function Faq() {
  return (
    <section id="faq" className="border-t hairline">
      <div className="container-luxe py-24">
        <div className="max-w-2xl">
          <p className="eyebrow">FAQ</p>
          <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
            Questions, answered.
          </h2>
        </div>
        <dl className="mt-12 grid gap-x-12 gap-y-9 md:grid-cols-2">
          {FAQS.map((f) => (
            <div key={f.q}>
              <dt className="font-display text-lg text-ink">{f.q}</dt>
              <dd className="mt-2 text-sm leading-relaxed text-stone">{f.a}</dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  );
}

/* ----------------------------------------------------------------------- */

function Hero() {
  return (
    <section className="relative">
      <div className="container-luxe py-16 md:py-20 md:pb-28">
        <div className="grid items-center gap-12 md:grid-cols-2">
        <div className="animate-rise">
          <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-2">
            <p className="eyebrow">
              {BRAND.eyebrow} · {BRAND.tagline}
            </p>
            <Link
              href="/how-it-works"
              className="text-sm text-brass transition-colors hover:text-ink"
            >
              How it works →
            </Link>
          </div>
          <h1 className="mt-5 font-display text-[2.7rem] leading-[1.05] tracking-tight sm:text-6xl">
            Look more{" "}
            <em className="not-italic text-brass">considered</em> — without
            becoming a fashion victim.
          </h1>
          <p className="mt-6 max-w-md text-lg leading-relaxed text-stone">
            {BRAND.name} is an AI-assisted men&apos;s personal styling atelier —{" "}
            <span className="text-ink">{BRAND.stylist.name}</span>, our lead
            stylist persona, is the voice behind every report. Share a few
            photos, answer honest questions, and receive colour analysis,
            photorealistic looks, tailoring notes, and a precise shopping list —
            each with the reason{" "}
            <span className="text-ink">why it works for you.</span> Or generate
            occasion looks and rebuild every piece in the constructor — then try
            catalogue items on your photo.
          </p>
          <div className="mt-9 flex flex-wrap items-center gap-3">
            <ButtonLink href="/create-look">Create a look</ButtonLink>
            <ButtonLink href="/start" variant="outline">
              Create my style report
            </ButtonLink>
          </div>
          <p className="mt-5 text-sm text-stone-soft">
            Sign up for {SIGNUP_BONUS} free credits — looks from{" "}
            {LOOK_SET_BUNDLES[0].credits} credits, try-on {CREDIT_COSTS.tryon}{" "}
            credit ·{" "}
            <Link
              href="/report/valetti-style-prospect-demo"
              className="text-brass transition-colors hover:text-ink"
            >
              See an example report →
            </Link>
          </p>
        </div>

        <HeroVisual />
        </div>
      </div>
    </section>
  );
}

function HeroVisual() {
  const palette = ["#6B6B47", "#9E5C3C", "#EFE6D3", "#27324A", "#B08A5B"];
  return (
    <div className="relative mx-auto w-full max-w-md animate-rise [animation-delay:120ms]">
      <div className="relative aspect-[4/5] overflow-hidden rounded-2xl border hairline shadow-[0_40px_80px_-40px_rgba(21,18,13,0.45)]">
        <Image
          src="/images/hero-editorial.png"
          alt="Editorial portrait of a man in a navy blazer and cream knit"
          fill
          priority
          sizes="(max-width: 768px) 100vw, 480px"
          className="object-cover object-top"
        />
        <div className="absolute right-4 top-4 z-10 flex flex-col items-end gap-2">
          <span className="rounded-full bg-paper/90 px-3 py-1.5 text-[11px] text-ink backdrop-blur-sm">
            autumn · warm · low contrast
          </span>
          <span className="hidden rounded-full border hairline bg-paper px-4 py-2 text-xs text-stone shadow-sm sm:inline-block">
            {lookCountForTier("premium")} looks · PDF · shopping list
          </span>
        </div>
      </div>

      {/* Floating style-profile card */}
      <div className="absolute -bottom-8 left-2 w-56 rounded-xl border hairline bg-paper/95 p-4 shadow-[0_24px_48px_-24px_rgba(21,18,13,0.4)] backdrop-blur-sm sm:-left-8 sm:w-60">
        <div className="flex items-center justify-between">
          <span className="eyebrow">Style profile</span>
        </div>
        <div className="mt-3 text-xs text-stone">Best colours</div>
        <div className="mt-2 flex gap-1.5">
          {palette.map((c) => (
            <span
              key={c}
              className="h-6 w-6 rounded-full border border-ink/10"
              style={{ background: c }}
            />
          ))}
        </div>
        <div className="mt-3 space-y-1.5">
          <Mini label="Silhouette" value="Tailored" />
          <Mini label="Hair" value="Textured crop" />
        </div>
      </div>

    </div>
  );
}

function Mini({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between border-b hairline pb-1.5 text-xs">
      <span className="text-stone-soft">{label}</span>
      <span className="text-ink">{value}</span>
    </div>
  );
}

function Marquee() {
  const items = [
    "Men's personal styling",
    "Photorealistic looks",
    "Look constructor",
    "Catalogue try-on",
    "Real shopping links",
  ];
  return (
    <div className="border-y hairline bg-ink text-paper">
      <div className="container-luxe flex flex-wrap items-center justify-center gap-x-10 gap-y-3 py-5 text-sm">
        {items.map((i, idx) => (
          <span key={i} className="flex items-center gap-10">
            <span className="text-paper/80">{i}</span>
            {idx < items.length - 1 && (
              <span className="hidden h-1 w-1 rounded-full bg-brass-soft sm:block" />
            )}
          </span>
        ))}
      </div>
    </div>
  );
}

function Problem() {
  return (
    <section className="container-luxe py-24">
      <div className="grid items-center gap-14 md:grid-cols-2">
        <div className="relative aspect-[4/3] overflow-hidden rounded-2xl border hairline">
          <Image
            src="/images/flatlay-essentials.png"
            alt="Flat lay of warm-toned menswear essentials"
            fill
            sizes="(max-width: 768px) 100vw, 560px"
            className="object-cover"
          />
        </div>
        <div>
          <p className="eyebrow">The problem</p>
          <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
            Most people want to look better. Few know exactly how.
          </h2>
          <div className="mt-6 space-y-5 text-lg leading-relaxed text-stone">
            <p>
              A classic stylist is expensive, time-consuming, and often feels
              like a service &ldquo;not for everyone.&rdquo; Ordinary fashion
              apps give you pretty pictures, but never explain{" "}
              <span className="text-ink">why</span> a look suits{" "}
              <span className="text-ink">you</span>.
            </p>
            <p>
              {BRAND.name} is different: a deep, honest analysis of your
              colouring, features, lifestyle and goals — turned into a calm,
              practical plan you can actually act on.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

function ReportProof() {
  const palette = ["#6B6B47", "#9E5C3C", "#EFE6D3", "#27324A", "#B08A5B"];
  const proofCards = [
    {
      eyebrow: "Start here",
      title: "3 changes with the highest return",
      body: "Replace black-and-white contrast with warm neutrals, keep silhouettes tailored, and make brown leather your default.",
    },
    {
      eyebrow: "Colour diagnosis",
      title: "Soft Autumn, not generic autumn",
      body: "Warm, muted, low-contrast colours make the face look healthier; optic white and cold black drain the complexion.",
    },
    {
      eyebrow: "Hair direction",
      title: "Texture over severity",
      body: "A textured crop and softer side profile sharpen the face without making the look feel corporate or dated.",
    },
    {
      eyebrow: "Buying plan",
      title: "Good · Better · Best shopping",
      body: "The report turns analysis into a practical capsule: what to buy first, what can wait, and where to spend.",
    },
  ];

  return (
    <section className="border-y hairline bg-cream/30">
      <div className="container-luxe py-24">
        <div className="flex flex-col justify-between gap-6 md:flex-row md:items-end">
          <div className="max-w-2xl">
            <p className="eyebrow">Inside the demo report</p>
            <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
              See the actual kind of advice you get before you sign up.
            </h2>
            <p className="mt-4 max-w-xl text-stone">
              Not a moodboard dump. Valetti turns your colouring, face, frame and
              lifestyle into specific decisions you can act on.
            </p>
          </div>
          <ButtonLink href="/report/valetti-style-prospect-demo" variant="outline">
            Open full demo report
          </ButtonLink>
        </div>

        <div className="mt-12 grid gap-4 lg:grid-cols-[1.15fr_0.85fr]">
          <div className="grid gap-px overflow-hidden rounded-2xl border hairline bg-line sm:grid-cols-2">
            {proofCards.map((card, index) => (
              <article key={card.title} className="bg-paper p-7">
                <div className="flex items-center justify-between gap-4">
                  <p className="text-[11px] font-medium uppercase tracking-[0.18em] text-brass">
                    {card.eyebrow}
                  </p>
                  <span className="font-display text-sm text-stone-soft">
                    {String(index + 1).padStart(2, "0")}
                  </span>
                </div>
                <h3 className="mt-4 font-display text-xl leading-snug">
                  {card.title}
                </h3>
                <p className="mt-3 text-sm leading-relaxed text-stone">
                  {card.body}
                </p>
              </article>
            ))}
          </div>

          <div className="rounded-2xl border hairline bg-paper p-5">
            <div className="rounded-xl bg-ink p-5 text-paper">
              <div className="flex items-center justify-between gap-4 text-[11px] uppercase tracking-[0.18em] text-paper/50">
                <span>Report excerpt</span>
                <span>Soft Autumn</span>
              </div>
              <h3 className="mt-4 font-display text-2xl leading-tight">
                Your first three moves
              </h3>
              <div className="mt-5 space-y-3">
                {[
                  "Move from black to warm navy, olive and tobacco.",
                  "Keep contrast soft around the face: cream over optic white.",
                  "Choose textured hair and clean tailoring over hard lines.",
                ].map((item, index) => (
                  <div key={item} className="flex gap-3 text-sm text-paper/75">
                    <span className="font-display text-brass-soft">
                      {String(index + 1).padStart(2, "0")}
                    </span>
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2">
              <div className="rounded-xl border hairline bg-cream/40 p-4">
                <div className="text-[11px] uppercase tracking-[0.18em] text-stone-soft">
                  Palette
                </div>
                <div className="mt-3 grid grid-cols-5 gap-1.5">
                  {palette.map((c) => (
                    <span
                      key={c}
                      className="aspect-square rounded-md border border-ink/10"
                      style={{ background: c }}
                    />
                  ))}
                </div>
                <p className="mt-3 text-xs leading-relaxed text-stone">
                  Warm, muted, low-contrast colours support the face.
                </p>
              </div>

              <div className="grid grid-cols-2 gap-3">
                {[
                  ["Look", "/images/look-work.png"],
                  ["Hair", "/images/demo/hair-textured-crop-side.png"],
                ].map(([label, src]) => (
                  <div key={label}>
                    <div className="relative aspect-[3/4] overflow-hidden rounded-xl border hairline bg-cream">
                      <Image
                        src={src}
                        alt={`${label} preview from demo report`}
                        fill
                        sizes="(max-width: 1024px) 45vw, 150px"
                        className="object-cover object-top"
                      />
                    </div>
                    <div className="mt-2 text-[11px] uppercase tracking-[0.16em] text-stone-soft">
                      {label}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function Understand() {
  const items = [
    ["Hair", "Which cuts suit your face — and which quietly date you."],
    ["Colours", "The tones that make you look healthy, and the ones that drain you."],
    ["Clothing", "What fits your age, profession, climate and goals."],
    ["Silhouette", "The fits, cuts and proportions that genuinely work."],
    ["Wardrobe", "The 5–10 pieces that unlock the most new outfits."],
    ["Mistakes", "The errors to fix first — before spending a cent."],
  ];
  return (
    <section className="border-y hairline bg-cream/40">
      <div className="container-luxe py-24">
        <div className="max-w-2xl">
          <p className="eyebrow">What you&apos;ll understand</p>
          <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
            Clear answers to the questions you&apos;ve been guessing at.
          </h2>
        </div>
        <div className="mt-14 grid gap-px overflow-hidden rounded-2xl border hairline bg-line sm:grid-cols-2 lg:grid-cols-3">
          {items.map(([title, body], i) => (
            <div
              key={title}
              className="group bg-paper p-8 transition-colors hover:bg-cream/60"
            >
              <div className="flex items-baseline gap-3">
                <span className="font-display text-sm text-brass">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <h3 className="font-display text-xl">{title}</h3>
              </div>
              <p className="mt-3 text-stone leading-relaxed">{body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function ImpactOfColour() {
  return (
    <section className="container-luxe py-24">
      <div className="grid gap-14 lg:grid-cols-[1.1fr_1fr] items-center">
        {/* Text Side */}
        <div className="order-2 lg:order-1">
          <p className="eyebrow">The Science of Colour</p>
          <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
            The wrong palette drains you.<br />
            The right one does the heavy lifting.
          </h2>
          <div className="mt-6 space-y-5 text-lg leading-relaxed text-stone">
            <p>
              Most men default to black, pure white, or stark navy. But if your
              natural colouring is warm and muted (like our model here), optic
              white and black will overpower you. They drain the skin, highlight
              fatigue, and make you look washed out.
            </p>
            <p>
              When you wear colours engineered for your specific 12-season
              profile — in this case, a Soft Autumn — the clothes harmonize
              with your undertone. Your skin looks healthier, your features are
              in focus, and your style reads as effortlessly expensive.
            </p>
          </div>
          
          <div className="mt-8 grid gap-4 sm:grid-cols-2">
            <div className="rounded-xl border border-line bg-paper p-5 opacity-80">
              <div className="flex items-center gap-2 font-display text-sm text-ink">
                <span className="flex h-5 w-5 items-center justify-center rounded-full bg-stone/10 text-stone-soft">✕</span>
                The Default (Wrong)
              </div>
              <p className="mt-2 text-xs leading-relaxed text-stone-soft">
                Cold light, stark contrast. Overpowers warm skin tones and highlights imperfections.
              </p>
            </div>
            <div className="rounded-xl border border-brass/30 bg-brass/5 p-5">
              <div className="flex items-center gap-2 font-display text-sm text-ink">
                <span className="flex h-5 w-5 items-center justify-center rounded-full bg-brass/20 text-brass">✓</span>
                The Valetti Palette
              </div>
              <p className="mt-2 text-xs leading-relaxed text-stone">
                Warm ecru and tobacco brown. Matches his DNA. Skin looks healthy, features are in focus.
              </p>
            </div>
          </div>
        </div>

        {/* Visual Side (Slider) */}
        <div className="order-1 lg:order-2">
          <div className="relative mx-auto w-full max-w-[460px]">
            <div className="relative aspect-[4/5] w-full rounded-2xl border hairline shadow-sm">
              <ImageComparisonSlider
                beforeImage="/images/hero-editorial-bad-palette.png"
                afterImage="/images/hero-editorial.png"
                beforeAlt="Incorrect cold high-contrast palette"
                afterAlt="Correct warm soft autumn palette"
              />
            </div>
            {/* Context Badge */}
            <div className="absolute -bottom-5 right-4 z-10 rounded-xl border hairline bg-paper/95 px-4 py-2 shadow-sm backdrop-blur-sm sm:-right-4">
              <div className="text-[10px] uppercase tracking-widest text-stone-soft">Profile</div>
              <div className="mt-1 font-display text-sm text-ink">Soft Autumn</div>
              <div className="text-xs text-stone">Warm undertone · Low contrast</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function HowItWorks() {
  const steps = [
    ["Answer", "A short questionnaire: age, city, lifestyle, goals, budget, and how bold you want to be."],
    ["Upload", "Add a few photos — front portrait and full length work best. Optional profile shot."],
    ["Analyse", "Our engine builds your Style Profile and grounds every recommendation in a reason."],
    ["Receive", "A structured report, infographic, photorealistic looks and a precise shopping list."],
  ];
  return (
    <section id="how" className="container-luxe py-24">
      <div className="flex flex-col items-start justify-between gap-6 md:flex-row md:items-end">
        <div className="max-w-xl">
          <p className="eyebrow">How it works</p>
          <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
            From a few questions to a finished plan in minutes.
          </h2>
        </div>
        <div className="flex flex-wrap gap-3">
          <ButtonLink href="/create-look">Create a look</ButtonLink>
          <ButtonLink href="/start" variant="outline">
            Start a report
          </ButtonLink>
        </div>
      </div>

      <div className="mt-16 grid gap-10 md:grid-cols-4">
        {steps.map(([title, body], i) => (
          <div key={title} className="relative">
            <div className="font-display text-5xl text-sand">
              {String(i + 1).padStart(2, "0")}
            </div>
            <h3 className="mt-3 font-display text-xl">{title}</h3>
            <p className="mt-2 text-sm leading-relaxed text-stone">{body}</p>
            {i < steps.length - 1 && (
              <div className="absolute right-0 top-6 hidden h-px w-1/2 bg-line md:block" />
            )}
          </div>
        ))}
      </div>
    </section>
  );
}

function LooksStudio() {
  const photoAssets = [
    {
      title: "Face portrait",
      body: "Natural daylight, face and hair clear — used for identity and colouring.",
      src: "/images/photo-example-good.png",
      alt: "Clear daylight portrait used as a face reference",
    },
    {
      title: "Full-length photo",
      body: "Head to toe, shot from chest height — looks and try-ons are rendered on you.",
      src: "/images/look-weekend.png",
      alt: "Full-length outfit reference for look generation",
    },
  ];
  const constructorMoves = [
    "Jacket, knit or shirt type",
    "Colour of each piece",
    "Sunglasses frame and lenses",
    "Tie, hat, belt or watch",
    "Shirt tucked in or untucked",
  ];

  return (
    <section id="create-look" className="border-y hairline bg-cream/40">
      <div className="container-luxe py-24">
        <div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end">
          <div className="max-w-2xl">
            <p className="eyebrow">Looks &amp; try-on</p>
            <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
              Generate looks on your photo — then rebuild every piece.
            </h2>
            <p className="mt-5 max-w-xl text-lg leading-relaxed text-stone">
              Create a Look builds a set of photorealistic outfits for an
              occasion. Open any look in the constructor and change a garment,
              colour or finishing detail without starting over. Or skip the set
              and try real catalogue pieces on yourself.
            </p>
          </div>
          <div className="flex flex-wrap gap-3">
            <ButtonLink href="/create-look">Create a look</ButtonLink>
            <ButtonLink href="/catalog" variant="outline">
              Try the catalog
            </ButtonLink>
          </div>
        </div>

        <div className="mt-14 grid gap-6 lg:grid-cols-2">
          <article className="flex flex-col rounded-2xl border hairline bg-paper p-7 sm:p-8">
            <p className="text-[11px] font-medium uppercase tracking-[0.18em] text-brass">
              Look constructor
            </p>
            <h3 className="mt-3 font-display text-2xl leading-snug">
              Rebuild a look piece by piece
            </h3>
            <p className="mt-3 text-sm leading-relaxed text-stone">
              Sets of {LOOK_SET_BUNDLES.map((b) => b.looks).join(", ")} looks —
              from {LOOK_SET_BUNDLES[0].credits} credits. Apply a constructor
              redraw for {CREDIT_COSTS.look_regen} credit.
            </p>

            <div className="mt-6 flex gap-2">
              {CONSTRUCTOR_ASSETS.map((piece) => (
                <div
                  key={piece.label}
                  className="relative aspect-square min-w-0 flex-1 overflow-hidden rounded-xl border hairline bg-cream/40"
                >
                  <Image
                    src={piece.src}
                    alt={piece.label}
                    fill
                    sizes="80px"
                    className="object-contain p-1.5"
                  />
                </div>
              ))}
            </div>
            <p className="mt-2 text-[11px] uppercase tracking-[0.16em] text-stone-soft">
              Jacket · trousers · shoes · tie · watch
            </p>

            <p className="mt-6 text-xs font-medium uppercase tracking-[0.16em] text-stone-soft">
              Photos you need
            </p>
            <div className="mt-3 grid gap-3 sm:grid-cols-2">
              {photoAssets.map((asset) => (
                <div
                  key={asset.title}
                  className="flex gap-3 rounded-xl border hairline bg-cream/30 p-3"
                >
                  <div className="relative h-16 w-12 shrink-0 overflow-hidden rounded-lg border hairline">
                    <Image
                      src={asset.src}
                      alt={asset.alt}
                      fill
                      sizes="48px"
                      className="object-cover object-top"
                    />
                  </div>
                  <div>
                    <div className="text-sm text-ink">{asset.title}</div>
                    <p className="mt-1 text-xs leading-relaxed text-stone">
                      {asset.body}
                    </p>
                  </div>
                </div>
              ))}
            </div>
            <p className="mt-3 text-xs leading-relaxed text-stone-soft">
              Already have a report? Reuse that profile — no new upload needed.
            </p>

            <ul className="mt-6 space-y-2 text-sm text-stone">
              {constructorMoves.map((item) => (
                <li key={item} className="flex items-start gap-2.5">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-brass" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </article>

          <article className="flex flex-col rounded-2xl border hairline bg-paper p-7 sm:p-8">
            <p className="text-[11px] font-medium uppercase tracking-[0.18em] text-brass">
              Catalogue try-on
            </p>
            <h3 className="mt-3 font-display text-2xl leading-snug">
              Try real pieces on your photo
            </h3>
            <p className="mt-3 text-sm leading-relaxed text-stone">
              Browse the menswear catalogue, add up to four items to an outfit,
              and render them together on your default full-length photo — on
              the original scene or in a clean studio. {CREDIT_COSTS.tryon}{" "}
              credit per try-on.
            </p>

            <div className="relative mt-6 aspect-[4/3] overflow-hidden rounded-xl border hairline">
              <Image
                src="/images/flatlay-essentials.png"
                alt="Warm-toned menswear essentials from the Valetti catalogue"
                fill
                sizes="(max-width: 1024px) 100vw, 520px"
                className="object-cover"
              />
            </div>

            <ol className="mt-6 space-y-3 text-sm text-ink">
              {[
                "Open Catalog and sign in.",
                "Add a full-length photo if you do not have one yet.",
                "Tap + Add to outfit on up to four pieces.",
                "Render on your photo — then read Carlo's verdict.",
              ].map((step, i) => (
                <li key={step} className="flex gap-3">
                  <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border hairline bg-cream/60 font-display text-xs text-brass">
                    {i + 1}
                  </span>
                  <span className="pt-0.5 leading-relaxed text-stone">
                    {step}
                  </span>
                </li>
              ))}
            </ol>
          </article>
        </div>
      </div>
    </section>
  );
}

function SampleReport() {
  return (
    <section id="sample" className="border-y hairline bg-ink text-paper">
      <div className="container-luxe grid items-center gap-14 py-24 md:grid-cols-2">
        <div>
          <p className="eyebrow !text-brass-soft">The deliverable</p>
          <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
            Not a pretty picture. A consultation.
          </h2>
          <p className="mt-5 max-w-md leading-relaxed text-paper/70">
            Every report is structured, explainable and practical — written in
            Carlo&apos;s voice, as if a thoughtful stylist had actually taken the
            time to know you.
          </p>
          <ul className="mt-8 space-y-3 text-paper/80">
            {[
              "Structured personal style profile",
              "Detailed report with the reason behind each call",
              "Clean infographic & colour palette",
              "Photorealistic look variations",
              "Shopping list with real product links",
              "Virtual try-on of recommended items",
            ].map((t) => (
              <li key={t} className="flex items-start gap-3">
                <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brass-soft" />
                <span>{t}</span>
              </li>
            ))}
          </ul>
          <div className="mt-9">
            <ButtonLink
              href="/report/valetti-style-prospect-demo"
              className="!bg-paper !text-ink hover:!bg-cream"
            >
              Open the example report
            </ButtonLink>
          </div>
        </div>

        <div className="rounded-2xl border border-paper/15 bg-ink-soft/60 p-6">
          <div className="flex items-center justify-between text-xs text-paper/50">
            <span>STYLE REPORT · PREMIUM</span>
            <span>Berlin · autumn palette</span>
          </div>
          <h3 className="mt-3 font-display text-2xl">
            Warm, modern, and quietly confident
          </h3>
          <div className="mt-5 grid grid-cols-5 gap-2">
            {["#6B6B47", "#9E5C3C", "#EFE6D3", "#27324A", "#B08A5B"].map((c) => (
              <div key={c} className="space-y-1.5">
                <div
                  className="aspect-square rounded-lg border border-paper/10"
                  style={{ background: c }}
                />
              </div>
            ))}
          </div>
          <div className="mt-6 grid grid-cols-3 gap-3">
            {[
              ["Work", "/images/look-work.png"],
              ["Dinner", "/images/look-dinner.png"],
              ["Weekend", "/images/look-weekend.png"],
            ].map(([c, src]) => (
              <div key={c}>
                <div className="relative aspect-[3/4] overflow-hidden rounded-lg border border-paper/10">
                  <Image
                    src={src}
                    alt={`${c} look`}
                    fill
                    sizes="(max-width: 768px) 30vw, 140px"
                    className="object-cover"
                  />
                </div>
                <div className="mt-2 text-xs text-paper/60">{c}</div>
              </div>
            ))}
          </div>
          <p className="mt-6 text-sm leading-relaxed text-paper/60">
            <span className="text-brass-soft">Why brown over black:</span>{" "}
            warm-toned leather ties your whole palette together far better than
            black ever will.
          </p>
        </div>
      </div>
    </section>
  );
}

function CapsulePreview() {
  return (
    <section className="border-y hairline bg-cream/20">
      <div className="container-luxe py-24">
        <div className="grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-end">
          <div className="max-w-2xl">
            <p className="eyebrow">The Wardrobe Matrix</p>
            <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
              We don&apos;t just give you outfits. We build a mathematical wardrobe.
            </h2>
            <p className="mt-5 text-lg leading-relaxed text-stone">
              Most apps generate random looks. We pick 5–10 core pieces and map out exactly how they combine into a full week of outfits, ensuring every item pulls its weight using the 60/30/10 proportion rule.
            </p>
          </div>

          <blockquote className="rounded-2xl border border-brass/30 bg-brass/5 p-6 lg:ml-auto lg:max-w-md">
            <svg
              className="h-6 w-6 text-brass-soft"
              fill="currentColor"
              viewBox="0 0 24 24"
              aria-hidden
            >
              <path d="M14.017 21v-7.391c0-5.704 3.731-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 9-10.609l.996 2.151c-2.433.917-3.996 3.638-3.996 5.849h4v10h-10z" />
            </svg>
            <p className="mt-4 font-display text-lg leading-relaxed text-ink">
              Good style isn&apos;t about fashion. It&apos;s the removal of
              visual noise between who you are and how you are perceived.
            </p>
            <footer className="mt-4 text-xs font-medium uppercase tracking-wider text-stone">
              — {BRAND.stylist.signature}
            </footer>
          </blockquote>
        </div>

        <div className="mt-14 grid gap-8 lg:grid-cols-[1fr_1.3fr]">
          {/* Proportions */}
          <div className="rounded-2xl border hairline bg-paper p-8 shadow-sm">
            <h3 className="font-display text-2xl">The 60/30/10 Rule</h3>
            <p className="mt-3 text-sm leading-relaxed text-stone">
              Every look is balanced by proportion, not just palette. 60% dominant base, 30% secondary anchor, 10% accent. This is how you mix colours without looking loud.
            </p>
            <div className="mt-8 flex h-14 w-full overflow-hidden rounded-xl border border-ink/10 shadow-sm">
              <div className="flex w-[60%] items-center justify-center bg-[#27324A] px-2 text-center text-[10px] uppercase tracking-widest text-white/90">
                60% Base
              </div>
              <div className="flex w-[30%] items-center justify-center bg-[#EFE6D3] px-2 text-center text-[10px] uppercase tracking-widest text-ink/80">
                30% Anchor
              </div>
              <div className="flex w-[10%] items-center justify-center bg-[#9E5C3C] px-2 text-center text-[10px] uppercase tracking-widest text-white/90">
                10%
              </div>
            </div>
            <ul className="mt-6 space-y-2 text-xs text-stone-soft">
              <li className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#27324A]" /> Navy trousers & blazer</li>
              <li className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#EFE6D3]" /> Cream merino crewneck</li>
              <li className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#9E5C3C]" /> Brown leather loafers</li>
            </ul>
          </div>

          {/* Matrix */}
          <div className="rounded-2xl border hairline bg-paper p-8 shadow-sm">
            <h3 className="font-display text-2xl">5 pieces = 4 outfits</h3>
            <p className="mt-3 text-sm leading-relaxed text-stone">
              Your custom capsule matrix shows you exactly what to wear for every context. No guessing, no standalone pieces that only work in one outfit.
            </p>
            <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4">
              {[
                { ctx: "Boardroom", pieces: ["Navy blazer", "White shirt", "Charcoal trousers"] },
                { ctx: "Dinner", pieces: ["Navy blazer", "Taupe knit", "Charcoal trousers"] },
                { ctx: "Smart Casual", pieces: ["Taupe knit", "White shirt", "Indigo denim"] },
                { ctx: "Weekend", pieces: ["Taupe knit", "Indigo denim", "Brown loafers"] },
              ].map((c) => (
                <div key={c.ctx} className="rounded-xl border hairline bg-cream/30 p-4">
                  <div className="text-[10px] uppercase tracking-wider text-brass">{c.ctx}</div>
                  <ul className="mt-3 space-y-1.5">
                    {c.pieces.map((p) => (
                      <li key={p} className="flex items-start gap-1.5 text-[11px] leading-tight text-stone">
                        <span className="mt-1 h-1 w-1 shrink-0 rounded-full bg-stone-soft" />
                        {p}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function Audience() {
  return (
    <section id="audience" className="container-luxe py-24">
      <div className="max-w-2xl">
        <p className="eyebrow">Who it&apos;s for</p>
        <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
          Built first for those who want to look right, not loud.
        </h2>
      </div>

      <div className="mt-14 grid gap-6 lg:grid-cols-3">
        <Card
          tag="Valetti focus"
          title="Men 25–55+"
          body="IT, consulting, business, freelance. Want to look modern, sharp and professional — without spending time on fashion. Often newly relocated and unsure where to even shop."
        />
        <Card
          tag="Also for"
          title="Expats & life changes"
          body="Relocating, changing jobs or social circles, dating, LinkedIn and conferences. People who need a look that fits a new country, climate and stage of life."
        />
        <Card
          tag="Business"
          title="Stylists, salons & shops"
          body="Generate white-label reports under your own brand and logo, add your own recommendations, and use your store's catalogue as the source of products."
          accent
        />
      </div>
    </section>
  );
}

function Card({
  tag,
  title,
  body,
  accent = false,
}: {
  tag: string;
  title: string;
  body: string;
  accent?: boolean;
}) {
  return (
    <div
      className={`rounded-2xl border p-8 transition-colors ${
        accent
          ? "border-brass/40 bg-brass/5"
          : "border-line bg-cream/30 hover:bg-cream/60"
      }`}
    >
      <span className="eyebrow">{tag}</span>
      <h3 className="mt-4 font-display text-2xl">{title}</h3>
      <p className="mt-3 leading-relaxed text-stone">{body}</p>
    </div>
  );
}

function Pricing() {
  const tiers: {
    name: string;
    price: string;
    cadence: string;
    features: string[];
    cta: string;
    href: string;
    featured: boolean;
    note?: string;
  }[] = [
    {
      name: "Starter Report",
      price: String(REPORT_COST.free),
      cadence: "credits",
      note: `Covered by your ${SIGNUP_BONUS} signup credits — leaves ${SIGNUP_BONUS - REPORT_COST.free} for a try-on`,
      features: [
        "Colour & hair analysis with reasons",
        "1 photorealistic preview look",
        "2 hairstyle previews on your photo",
        `Virtual try-on (${CREDIT_COSTS.tryon} credit each)`,
        "No share link, capsule, or PDF",
      ],
      cta: "Try it free",
      href: "/start",
      featured: false,
    },
    {
      name: "Basic report",
      price: String(REPORT_COST.basic),
      cadence: "credits",
      features: [
        "Full style profile & colour story",
        "Hair, silhouette & fit, with reasons",
        "3 photorealistic looks",
        "Shopping list + PDF export",
      ],
      cta: "Get Basic",
      href: "/start",
      featured: false,
    },
    {
      name: "Lookbook",
      price: String(REPORT_COST.lookbook),
      cadence: "credits",
      features: [
        "Everything in Basic",
        `${lookCountForTier("lookbook")} photorealistic looks`,
        "Capsule wardrobe + week matrix",
        "Finishing kit: shoes, belts, ties and a watch",
        `Virtual try-on (${CREDIT_COSTS.tryon} credit each)`,
        "Good · Better · Best buying plan",
        "4 hairstyle previews on your photo (front + side)",
      ],
      cta: "Get Lookbook",
      href: "/start",
      featured: true,
    },
    {
      name: "Premium",
      price: String(REPORT_COST.premium),
      cadence: "credits",
      features: [
        "Everything in Lookbook",
        `${lookCountForTier("premium")} photorealistic looks`,
        "Finishing kit: shoes, belts, ties and a watch",
        "4 facial-hair previews on your photo",
        "2 optical + 2 sunglasses previews",
        "Deeper grooming guidance",
      ],
      cta: "Get Premium",
      href: "/start",
      featured: false,
    },
  ];
  const starter = CREDIT_PACKAGES[0];
  return (
    <section id="pricing" className="border-y hairline bg-cream/40">
      <div className="container-luxe py-24">
        <div className="max-w-2xl">
          <p className="eyebrow">Pricing</p>
          <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
            Pay for the work, not a subscription.
          </h2>
          <p className="mt-4 text-stone">
            {BRAND.name} runs on credits — a report costs credits by tier, and
            each virtual try-on or re-render is {CREDIT_COSTS.tryon} credit. New
            accounts get {SIGNUP_BONUS} free credits, and packs start at{" "}
            <SubCurrencyPrice prices={starter.price} /> for {starter.credits}{" "}
            credits.{" "}
            <Link href="/pricing" className="text-brass hover:text-ink">
              See full pricing &amp; credit packs →
            </Link>
          </p>
        </div>

        <div className="mt-14 grid gap-6 lg:grid-cols-4">
          {tiers.map((t) => (
            <div
              key={t.name}
              className={`relative flex flex-col rounded-2xl border p-7 ${
                t.featured
                  ? "border-ink bg-ink text-paper"
                  : "border-line bg-paper"
              }`}
            >
              {t.featured && (
                <span className="absolute -top-3 left-7 rounded-full bg-brass px-3 py-1 text-[11px] uppercase tracking-wider text-paper">
                  Most popular
                </span>
              )}
              <div className="text-sm tracking-wide opacity-80">{t.name}</div>
              <div className="mt-3 flex items-baseline gap-2">
                <span className="font-display text-4xl">{t.price}</span>
                {t.cadence && (
                  <span
                    className={`text-xs ${t.featured ? "text-paper/60" : "text-stone-soft"}`}
                  >
                    {t.cadence}
                  </span>
                )}
              </div>
              {t.note && <p className="mt-1 text-xs text-brass">{t.note}</p>}
              <ul className="mt-6 flex-1 space-y-3 text-sm">
                {t.features.map((f) => (
                  <li key={f} className="flex items-start gap-2.5">
                    <span
                      className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${
                        t.featured ? "bg-brass-soft" : "bg-brass"
                      }`}
                    />
                    <span className={t.featured ? "text-paper/85" : "text-stone"}>
                      {f}
                    </span>
                  </li>
                ))}
              </ul>
              <Link
                href={t.href}
                className={`mt-7 inline-flex items-center justify-center rounded-full px-5 py-3 text-sm transition-all ${
                  t.featured
                    ? "bg-paper text-ink hover:bg-cream"
                    : "border border-ink/25 text-ink hover:bg-ink hover:text-paper"
                }`}
              >
                {t.cta}
              </Link>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function Principles() {
  const items = [
    ["Personal", "Recommendations are built around you — not generic fashion advice."],
    ["Explainable", "Every important call comes with the reason behind it."],
    ["Practical", "Actionable output: what to wear, buy, combine and fix first."],
    ["Private", "Your face and body are sensitive data. Designed GDPR-first from day one."],
  ];
  return (
    <section className="container-luxe py-24">
      <div className="max-w-2xl">
        <p className="eyebrow">Principles</p>
        <h2 className="mt-4 font-display text-3xl leading-tight sm:text-4xl">
          Quality over wow-effect.
        </h2>
        <p className="mt-4 text-lg leading-relaxed text-stone">
          AI imagery matters — but it should never replace a genuine analysis.
          This is a consultant, not a toy.
        </p>
      </div>

      <div className="mt-14 grid items-center gap-12 md:grid-cols-[1fr_1.4fr]">
        <div className="relative aspect-[4/3] w-full overflow-hidden rounded-2xl border hairline">
          <Image
            src={BRAND.stylist.atelier}
            alt="Editorial atelier scene — the world of Valetti"
            fill
            sizes="(max-width: 768px) 100vw, 420px"
            className="object-cover"
          />
          <span className="absolute bottom-3 left-3 rounded-full bg-paper/90 px-3 py-1.5 text-[11px] text-ink backdrop-blur-sm">
            The Valetti atelier
          </span>
        </div>
        <div className="grid gap-px overflow-hidden rounded-2xl border hairline bg-line sm:grid-cols-2">
          {items.map(([t, b]) => (
            <div key={t} className="bg-paper p-7">
              <h3 className="font-display text-xl">{t}</h3>
              <p className="mt-2 text-sm leading-relaxed text-stone">{b}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function FinalCTA() {
  return (
    <section className="border-t hairline bg-ink text-paper">
      <div className="container-luxe py-24 text-center">
        <p className="eyebrow !text-brass-soft">Your style, decoded</p>
        <h2 className="mx-auto mt-5 max-w-2xl font-display text-4xl leading-tight sm:text-5xl">
          See what genuinely suits you — and why.
        </h2>
        <p className="mx-auto mt-5 max-w-md text-paper/70">
          Sign up for {SIGNUP_BONUS} free credits — Starter Report costs{" "}
          {REPORT_COST.free}, try-on {CREDIT_COSTS.tryon} credit. No subscription.
        </p>
        <div className="mt-9 flex flex-wrap justify-center gap-3">
          <ButtonLink
            href="/create-look"
            className="!bg-paper !text-ink hover:!bg-cream"
          >
            Create a look
          </ButtonLink>
          <ButtonLink
            href="/start"
            variant="outline"
            className="!border-paper/35 !text-paper hover:!border-paper hover:!bg-paper hover:!text-ink"
          >
            Create my style report
          </ButtonLink>
        </div>
        <p className="mt-6 text-sm text-paper/50">— {BRAND.stylist.signature}</p>
      </div>
    </section>
  );
}
