-- Persist Carlo's expert read alongside the try-on it describes, so the verdict
-- survives page reloads and can be shown in history / the gallery. Generated by
-- /api/tryon/opinion after the render and written back to the tryon row.

alter table public.tryons
  add column if not exists opinion jsonb;
